# Generated by Django 4.2.7 on 2023-11-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='city_name',
            new_name='name',
        ),
    ]
